from src.phonebook import Phonebook


test_phone_book = Phonebook()
test_phone_book.add("Carlos", "333")
test_phone_book.add("Mayara", "111")
test_phone_book.add("Wayara", "110")
test_phone_book.add("Paulo", "210")
# test_phone_book.add("Carlos", "222")
# print(test_phone_book.lookup('Carlos'))
# print(test_phone_book.get_names)
# print(test_phone_book.entries)
# print(test_phone_book.change_number('Carlos', '222'))
# print(test_phone_book.entries)
print(test_phone_book.add("Neto", "444"))
print(list(test_phone_book.get_numbers()))
print(list(test_phone_book.entries.values()))
# print(test_phone_book.entries.values() == test_phone_book.get_numbers())
# print(test_phone_book.get_numbers())
# print(test_phone_book.get_phonebook_sorted())
# print(test_phone_book.get_name_by_number("222"))
# print(list(test_phone_book.entries.keys()))
# print(test_phone_book.clear())
# print(len(test_phone_book.entries))
# print(test_phone_book.search("Neto"))
# print(test_phone_book.search("Carlos"))
# print(test_phone_book.search("Car"))
print(test_phone_book.get_phonebook_sorted())
print(dict(sorted(test_phone_book.entries.items())))
